/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JList;



/**
 *
 * @author PBachta
 */
public final class ListaAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form ListaAppFrame
     */
    public ListaAppFrame() {
        initComponents();
        uzupelnianieListy();   //włącza metode uzupełnianie listy
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista1ScrollPane = new javax.swing.JScrollPane();
        //edytowane:
        lista1 = new javax.swing.JList(modelListy);
        dodajDoListyButton = new javax.swing.JButton();
        dodajDoListyTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        komunikatLabel = new javax.swing.JTextArea();
        infoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        //edytowane:
        lista1.setModel(modelListy);
        lista1.setVisibleRowCount(10);
        lista1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista1ValueChanged(evt);
            }
        });
        lista1ScrollPane.setViewportView(lista1);

        dodajDoListyButton.setText("Dodaj do Listy");
        dodajDoListyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajDoListyButtonActionPerformed(evt);
            }
        });

        dodajDoListyTextField.setToolTipText("Wpisz nazwę zawierającą od 3 do 10 znaków");
        dodajDoListyTextField.setName(""); // NOI18N
        dodajDoListyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dodajDoListyTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dodajDoListyTextFieldKeyTyped(evt);
            }
        });

        komunikatLabel.setEditable(false);
        komunikatLabel.setColumns(20);
        komunikatLabel.setRows(5);
        jScrollPane1.setViewportView(komunikatLabel);

        jLabel1.setText("Od 3 do 10 znaków");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lista1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dodajDoListyButton)
                    .addComponent(dodajDoListyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dodajDoListyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(dodajDoListyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lista1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajDoListyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajDoListyButtonActionPerformed
        String wpisanyText = dodajDoListyTextField.getText();  //pobiera wpisany text z pola tekstowego
        if(wpisanyText.length() > 3)   //jeśli długość tekstu jest większa od 3 znaków
        {
            modelListy.addElement(wpisanyText);         //dodaje pobrany text do listy
            infoLabel.setText("Dodano "+wpisanyText+" do Listy");
        }
        else 
            infoLabel.setText("Za mała ilość znaków");
        
    }//GEN-LAST:event_dodajDoListyButtonActionPerformed

    private void lista1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista1ValueChanged
        if (!evt.getValueIsAdjusting())  //funkcja która mówi czy najechaliśmy klikniętą myszką, my chcemy wiedzieć jak puścimy myeszkę (wybierzemy element) więc negacja
        {
            Object [] zaznaczonePola = ((JList)evt.getSource()).getSelectedValues();  //pobiera źródła z zaznaczonych pól bo możemy zaznaczyć wiele, przy możliwośći zaznaczania jednego wystarczy getSelectedValue
            
            String wybrane = "";        //nowy string do przechowywania wartości
            
            for (int i=0; i<zaznaczonePola.length; i++)   //pętla idąca po wszytskich zaznaczonych elementach
                wybrane += (String)zaznaczonePola[i]+'\n';  //i dodaje je do stringa "wybrane"
            
            komunikatLabel.setText("Zaznaczone pola to:"+'\n'+wybrane);   //wyświetla wybrane elementy w polu tekstowym
        } 
    }//GEN-LAST:event_lista1ValueChanged

    private void dodajDoListyTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dodajDoListyTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)   //po wciśnięciu ENTER w polu tekstowym
            dodajDoListyButton.doClick();           //naciska przycisk Dodaj do Listy
    }//GEN-LAST:event_dodajDoListyTextFieldKeyPressed

    private void dodajDoListyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dodajDoListyTextFieldKeyTyped
        if (dodajDoListyTextField.getText().length() > 9) //jeśli długość tekstu w polu tekstowym jest większa od 10
            evt.consume();          //consume, nie dodawaj więcej znaków
    }//GEN-LAST:event_dodajDoListyTextFieldKeyTyped
 
//____Funkcja do uzupełniania listy w elementy podane w stringu elementy listy zadeklarowanej w zmiennych (na dole)_______    
public void uzupelnianieListy()   
{
     for (int i = 0; i < elementyListy.length; i++)
        modelListy.addElement(elementyListy[i]);
}
//_________________________________________________________________________________    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListaAppFrame().setVisible(true);
//            }
//        });
    }

    
    private final String[] elementyListy = new String[] {"Pozycja 1","Pozycja 2", "Pozycja 3", "Pozycja 4", "Pozycja 5",
    "Pozycja 6", "Pozycja 7","Pozycja 8", "Pozycja 9", "Pozycja 10" };  //lista elementów do wpisania do listy
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajDoListyButton;
    private javax.swing.JTextField dodajDoListyTextField;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea komunikatLabel;
    private javax.swing.JList<String> lista1;
    final DefaultListModel modelListy = new DefaultListModel();  //tworzenie nowego modelu listy
    private javax.swing.JScrollPane lista1ScrollPane;
    // End of variables declaration//GEN-END:variables
}
