/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author PBachta
 */
public class ToolbarAppFrame extends JFrame {

    /**
     * Creates new form ToolbarAppFrame
     */
    public ToolbarAppFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        koloryGroup = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        zielonyButton = new javax.swing.JToggleButton();
        niebieskiButton = new javax.swing.JToggleButton();
        czerwonyButton = new javax.swing.JToggleButton();
        wylaczKolorButton = new javax.swing.JToggleButton();
        resetButton = new javax.swing.JButton();

        koloryGroup.add(zielonyButton);
        koloryGroup.add(niebieskiButton);
        koloryGroup.add(czerwonyButton);
        koloryGroup.add(wylaczKolorButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        toolBar.setRollover(true);
        toolBar.setAlignmentY(0.5F);

        zielonyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Ikony/zielony.gif"))); // NOI18N
        zielonyButton.setFocusable(false);
        zielonyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zielonyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zielonyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zielonyButtonActionPerformed(evt);
            }
        });
        toolBar.add(zielonyButton);

        niebieskiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Ikony/niebieski.gif"))); // NOI18N
        niebieskiButton.setFocusable(false);
        niebieskiButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        niebieskiButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        niebieskiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niebieskiButtonActionPerformed(evt);
            }
        });
        toolBar.add(niebieskiButton);

        czerwonyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Ikony/czerwony.gif"))); // NOI18N
        czerwonyButton.setFocusable(false);
        czerwonyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        czerwonyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        czerwonyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czerwonyButtonActionPerformed(evt);
            }
        });
        toolBar.add(czerwonyButton);

        wylaczKolorButton.setText("Wyłączenie kolorowania");
        wylaczKolorButton.setFocusable(false);
        wylaczKolorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wylaczKolorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wylaczKolorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylaczKolorButtonActionPerformed(evt);
            }
        });
        toolBar.add(wylaczKolorButton);

        resetButton.setText("Reset");
        resetButton.setFocusable(false);
        resetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        toolBar.add(resetButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zielonyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zielonyButtonActionPerformed
        setFlagaKursor(true);  //flaga do zmiany kursora po najechaniu na panel
        setKolor(Color.GREEN); // ustawienie koloru na jaki ma być malowane
        kursor();       //wywołanie metody kursor
    }//GEN-LAST:event_zielonyButtonActionPerformed

    private void niebieskiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niebieskiButtonActionPerformed
        setFlagaKursor(true);   //flaga do zmiany kursora po najechaniu na panel
        setKolor(Color.BLUE);   // ustawienie koloru na jaki ma być malowane
        kursor();       //wywołanie metody kursor
    }//GEN-LAST:event_niebieskiButtonActionPerformed

    private void czerwonyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czerwonyButtonActionPerformed
        setFlagaKursor(true);   //flaga do zmiany kursora po najechaniu na panel
        setKolor(Color.RED);    // ustawienie koloru na jaki ma być malowane
        kursor();       //wywołanie metody kursor
    }//GEN-LAST:event_czerwonyButtonActionPerformed

    private void wylaczKolorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wylaczKolorButtonActionPerformed
        setFlagaKursor(false);  //flaga do zmiany kursora po najechaniu na panel
        kursor();       //wywołanie metody kursor
    }//GEN-LAST:event_wylaczKolorButtonActionPerformed

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        panel.setBackground(kolor);   //zmienia kolor panela na aktualnie wybrany
    }//GEN-LAST:event_panelMousePressed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        setFlagaKursor(false);
        setKolor(toolBar.getBackground());   //ustawienie koloru na taki jakie jest tło
        panel.setBackground(kolor);  //ustawienie koloru panela taki jak kolor tła
        kursor();
    }//GEN-LAST:event_resetButtonActionPerformed

//_____Funkcja zmienia kursor jak kolor jest zaznaczony i najedziemy na panel______

private void kursor()
{
    if (isFlagaKursor())
        panel.setCursor(Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/AppPackage/Ikony/kursorek.png")).getImage(), new Point(0,0), "kursorek"));
    else
        panel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}
//____________________________________    

//___________setter i getter dla koloru____________
    public Color getKolor() {
        return kolor;
    }    

    public void setKolor(Color kolor) {
        this.kolor = kolor;
    }

//________________________________________________

//__________________setter i getter dla flagi kursora__________

    public boolean isFlagaKursor() {
        return flagaKursor;
    }

    public void setFlagaKursor(boolean flagaKursor) {
        this.flagaKursor = flagaKursor;
    }
//_____________________________________________________


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToolbarAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToolbarAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToolbarAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToolbarAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolbarAppFrame().setVisible(true);
            }
        });
    }
    private Color kolor = null;  //zmienna do określania jaki kolor jest wybrany
    private boolean flagaKursor = false;  //flaga do określania czy kursor ma się zmienić czy nie
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton czerwonyButton;
    private javax.swing.ButtonGroup koloryGroup;
    private javax.swing.JToggleButton niebieskiButton;
    private javax.swing.JPanel panel;
    private javax.swing.JButton resetButton;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JToggleButton wylaczKolorButton;
    private javax.swing.JToggleButton zielonyButton;
    // End of variables declaration//GEN-END:variables
}
